RunFAIRSECO:
  needs: [RunTortellini, RunSBOM]
  runs-on: ubuntu-latest
  permissions:
    contents: write

  steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: SecureSECO/FAIRSECO
        path: FAIRSECO_Assets

    # Download required artifacts from previous jobs
    - name: Download Tortellini result
      uses: actions/download-artifact@v4
      with:
        name: tortellini-result
        path: .tortellini/out

    - name: Download SBOM result
      uses: actions/download-artifact@v4
      with:
        name: SBOM.spdx
        path: ./SBOM/

    # Run FAIRSECO
    - uses: SecureSECO/FAIRSECO@v1.0.2
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}

    # Debug: list all files (optional but recommended)
    - name: Debug FAIRSECO output
      run: ls -laR

    # Upload results
    - uses: actions/upload-artifact@v4
      with:
        name: FAIRSECO Result
        path: .FAIRSECO/
        include-hidden-files: true
        if-no-files-found: warn

    # Commit and push history
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git pull
        git add -f ./.fairseco_history.json
        git commit --allow-empty -m "Update FAIRSECO history file"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
